### ISSUE TITLE
Compile error on MacOS

### ISSUE THREAD

**Issue by ericli2333** [nju-websoft/NJU_DBPractice#2]
![QQ_1731296983732](https://github.com/user-attachments/assets/e6be65f5-9ebe-4b53-9dcd-06bd2662c336)
I met some trouble when compiling this project on MacOS. It told me that there is a sytax error in `src/parser/yacc.y`
I'm pretty sure that I have installed all the kits to compile according to the README.

**Comment by ziqiwww** [comment]
it seems the Bison version is not compatible. could you upgrade it to 3.0+ and try again? (bison 3.8 on my mac)

**Comment by ericli2333** [comment]
That's the problem. The MacOS uses bison 2.3 by default. If you only use command `brew install bison`, it won't set the  PATH correctly. So it would be better to configure it in the CMakeList.txt explicitly. I'll make a pull request later which can solve this problem.
