### ISSUE TITLE
Page 的 FreePage 链表应当为双向链表以适应 InsertRecord(rid, record) 的指定插入行为

### ISSUE THREAD

**Issue by top-mind** [nju-websoft/NJU_DBPractice#5]
InsertRecord(rid, record) 用法可以使任意空闲页占满，空闲页表应当为双向链表以支持删除非表头元素的行为。

**Comment by ziqiwww** [comment]
InsertRecord(rid, record) will ONLY be used in a specific scenario during recovery: when a transaction aborts a deletion, the DBMS must recover the deleted record using the same RID, making the insertion appropriate in this case.

**Comment by top-mind** [comment]
My understanding is that transaction rollback logic ensures `tab_hdl_.next_free_page_ == rid.PageId()` in `InsertRecord(rid, record)`, right?

**Comment by ziqiwww** [comment]
if the record is deleted from a full page, the answer is yes, otherwise the next_free_page is uncertain
